doc-warnings: yes
test-warnings: no
strictness: low

pylint:
  disable:
    - too-few-public-methods
    - no-self-use
    - too-many-instance-attributes
    - invalid-name
    - missing-docstring
    - star-args
    - logging-format-interpolation
    - bad-builtin
ignore-paths:
  - docs
pep8:
  disable:
    - E731
    - E126
    - E128
    - E115
    - N802